mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('webmonit/', include('webmonit.urls')),
]

webmonit/urls.py
from django.urls import path

from . import views

app_name = 'webmonit'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:page_id>/details/', views.detail, name='detail'),
    path('<int:page_id>/logs/', views.page_log, name='page_log'),
    path('problems/', views.pages_with_problem, name='problems'),
    path('create/', views.create, name='create'),
    path('<int:page_id>/edit/', views.edit, name='edit'),
    path('<int:page_id>/delete/', views.delete, name='delete'),

    path('page-list/', views.pageList, name="task-list"),
    path('page-detail/<str:pk>/', views.pageDetail, name="task-detail"),
    path('page-create/', views.pageCreate, name="task-create"),
    path('page-update/<str:pk>/', views.pageUpdate, name="task-update"),
    path('page-delete/<str:pk>/', views.pageDelete, name="task-delete"),
]

webmonit/models.py
import json
import requests
from django.db import models
from django_celery_beat.models import PeriodicTask, IntervalSchedule
from requests.exceptions import HTTPError

from django.utils import timezone
import datetime


class Page(models.Model):
    name = models.TextField(max_length=50)
    url = models.TextField()
    status = models.IntegerField(default=0)
    frequency = models.IntegerField(default=60)
    monit_content = models.BooleanField(default=False)
    monit_instance = models.BooleanField(default=False)
    content = models.JSONField
    task = models.OneToOneField(
        PeriodicTask,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def setup_task(self):
        t, _ = IntervalSchedule.objects.get_or_create(every=self.frequency, period='minutes')
        self.task = PeriodicTask.objects.create(
            name=self.name,
            task='check_page',
            enabled=True,
            interval=t,
            args=json.dumps([self.id]),
            start_time=timezone.now()
        )
        self.save()

    def delete(self, *args, **kwargs):
        if self.task is not None:
            self.task.delete()
        return super(self.__class__, self).delete(*args, **kwargs)

    def __str__(self):
        return self.url

    def is_available(self):
        """Check status of the webpage"""
        try:
            response = requests.get(self.url)
            status = response.status_code
            content = response.text
            description = response.reason + "\n"
        except HTTPError as http_err:
            status = 999
            content = self.content
            description = f'HTTP error occurred: {http_err}'
        except Exception as err:
            status = 999
            content = self.content
            description = f'HTTP error occurred: {err}'
        return status, content, description

    def is_instance_changed(self, name, url, frequency):
        """Check if name url frequency of the Page was changed"""
        message = ""
        if self.name != name:
            message += f"name was changed from {self.name} to {name} \n"
        if self.url != url:
            message += f"url was changed from {self.url} to {url} \n"
        if self.frequency != frequency:
            message += f"frequency was changed from {self.frequency} to {frequency}"
            t, _ = IntervalSchedule.objects.get_or_create(every=self.frequency, period='minutes')
            self.task.enabled = True
            self.task.interval = t
            self.task.save()
        return message != "", message

    def is_content_changed(self, content):
        """Check if page content was changed"""
        message = ""
        if self.content != content:
            message += "Page content was changed"
        return message != "", message

    def check_page(self):
        stat, cont, desc = self.is_available()
        if self.monit_content:
            cont_changed, cont_message = self.is_content_changed(cont)
        else:
            cont_changed, cont_message = False, ""

        if self.status != stat or cont_changed:
            p = PageLog(
                page=self,
                status_changes=self.status != stat,
                status=stat,
                content_changes=cont_changed,
                description=desc + cont_message
            )
            p.save()
            self.content = cont
            self.status = stat
            self.save()
        return stat


class PageLog(models.Model):
    def __STR__(self):
        return f'{self.page} status: {self.status}'

    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    check_time = models.DateTimeField(default=datetime.datetime.now, blank=True)
    status = models.IntegerField(default=200)
    content_changes = models.BooleanField(default=False)
    page_changes = models.BooleanField(default=False)
    status_changes = models.BooleanField(default=False)
    description = models.TextField(default='None')

webmonit/forms.py
from django.forms import ModelForm

from .models import Page

class CreatePageForm(ModelForm):
    class Meta:
        model = Page
        fields = ['name', 'url', 'frequency']

webmonit/views.py
from django.shortcuts import get_object_or_404, render, HttpResponseRedirect
from .models import Page, PageLog
from django.db.models import Q
from .forms import CreatePageForm
from django.http import JsonResponse
from django.shortcuts import render

from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import PageSerializer

def index(request):
    observed_pages = Page.objects.all()
    context = {
        'Pages': observed_pages,
    }
    return render(request, 'webmonit/index.html', context)


def detail(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    return render(request, 'webmonit/detail.html', {'page': page})


def page_log(request, page_id):
    page_logs = PageLog.objects.filter(page__pk=page_id)
    context = {
        'Logs': page_logs
    }
    return render(request, 'webmonit/logs.html', context)

def pages_with_problem(request):
    pages = Page.objects.filter(~Q(status=200))
    context = {
        'Pages': pages
    }
    return render(request, 'webmonit/problems.html', context)

def create(request):
    if request.method == 'POST':
        form = CreatePageForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/webmonit/")
    else:
        form = CreatePageForm()

    context = {'form' : form }
    return render(request, 'webmonit/create.html', context)

def edit(request, page_id):
    page = get_object_or_404(Page, pk=page_id)
    monit_instance = page.monit_instance
    monit_content = page.monit_content
    if request.method == 'POST':
        form = CreatePageForm(request.POST, instance=page)
        if form.is_valid():
            post = form.instance
            post.monit_instance = monit_instance
            post.monit_content = monit_content
            post.save()
            return HttpResponseRedirect("/webmonit/")
    else:
        form = CreatePageForm(instance=page)

    context = {'form' : form}
    return render(request, 'webmonit/edit.html', context)


def delete(request, page_id):
    context = {}
    page = get_object_or_404(Page, pk=page_id)
    if request.method == 'POST':
        page.delete()
        return HttpResponseRedirect("/webmonit/")
    return render(request, 'webmonit/delete.html', context)


@api_view(['GET'])
def pageOverview(request):
	webmonit_urls = {
		'List':'/page-list/',
		'Detail View':'/page-detail/<str:pk>/',
		'Create':'/page-create/',
		'Update':'/page-update/<str:pk>/',
		'Delete':'/page-delete/<str:pk>/',
		}
	return Response(webmonit_urls)


@api_view(['GET'])
def pageList(request):
	pages = Page.objects.all().order_by('-id')
	serializer = PageSerializer(pages, many=True)
	return Response(serializer.data)

@api_view(['GET'])
def pageDetail(request, pk):
	pages = Page.objects.get(id=pk)
	serializer = PageSerializer(pages, many=False)
	return Response(serializer.data)


@api_view(['POST'])
def pageCreate(request):
	serializer = PageSerializer(data=request.data)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)

@api_view(['POST'])
def pageUpdate(request, pk):
	page = Page.objects.get(id=pk)
	serializer = PageSerializer(instance=page, data=request.data)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def pageDelete(request, pk):
	page = Page.objects.get(id=pk)
	page.delete()

	return Response('Item succsesfully delete!')

webmonit/templates/webmonit/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="'utf-8">
        <meta http-equiv="content-type" content="text/html"; charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>

        <!-- Bootstrap-CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    </head>
    <body>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Pages monitoring</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'webmonit:index' %}">Home</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'webmonit:problems' %}">Problems</a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'webmonit:create' %}">Add page to monit</a></li>
                    </ul>
                </div><!--/.navbar-collapse -->
            </div>
        </nav>

        <div class="container">
            {% block main %}{% endblock %}
        </div>
    </body>
</html>

webmonit/templates/webmonit/create.html
{% extends "webmonit/base.html" %}
{% load widget_tweaks %}

{% block title %}Add page to monit{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add page to monitoring</h3>
            </div>
                
            <form method="POST">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Enter page name</label>
                                {% render_field form.name class="form-control" rows="1" %}
                            </div>
                            <div class="form-group">
                                <label>Enter page url</label>
                                {% render_field form.url class="form-control" rows="1" %}
                            </div>
                            <div class="form-group">
                                <label>How often we shell check page (in minutes)</label>
                                {% render_field form.frequency%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <hr />
                        <div class="col-lg-4">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/delete.html
{% extends "webmonit/base.html" %}
{% load widget_tweaks %}

{% block title %}Add page to monit{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Delete Page</h3>
            </div>

                <form method="POST">
                    {% csrf_token %}
                    Are you want to delete this page?
                    <input type="submit" value="Yes" />
                    <a href="/webmonit/">Cancel </a>
                </form>
        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/detail.html
{% extends "webmonit/base.html" %}


{% block title %}Details{% endblock %}
{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Page details</h3>
            </div>
            <ul class="list-group">
                <li class="list-group-item">
                    <strong>{{ page.name}}</strong>
                </li>
                <li class="list-group-item">{{ page.url}}</li>
                <li class="list-group-item">{{ page.status}}</li>
            </ul>

        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/edit.html
{% extends "webmonit/base.html" %}
{% load widget_tweaks %}

{% block title %}Add page to monit{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Add page to monitoring</h3>
            </div>

            <form method="POST">
                {% csrf_token %}
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Enter page name</label>
                                {% render_field form.name class="form-control" rows="1" %}
                            </div>
                            <div class="form-group">
                                <label>Enter page url</label>
                                {% render_field form.url class="form-control" rows="1" %}
                            </div>
                            <div class="form-group">
                                <label>How often we shell check page (in minutes)</label>
                                {% render_field form.frequency%}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <hr />
                        <div class="col-lg-4">
                            <button type="submit" class="btn btn-info">Submit</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/index.html
{% extends "webmonit/base.html" %}

{% block title %}Homepage{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">webpages</h3>
            </div>

            <ul class="list-group">
                {% for page in Pages %}
                <li class="list-group-item">
                    <strong>{{ page.name }}</strong>
                    <span class="pull-right">
                        <a href="{% url 'webmonit:page_log' page.id %}" class="btn btn-info btn-xs">logs</a>
                        <a href="{% url 'webmonit:detail' page.id %}" class="btn btn-default btn-xs">details</a>
                        <a href="{% url 'webmonit:edit' page.id %}" class="btn btn-default btn-xs">edit</a>
                        <a href="{% url 'webmonit:delete' page.id %}" class="btn btn-danger btn-xs">delete</a> &nbsp;&nbsp;
                    </span>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/logs.html
{% extends "webmonit/base.html" %}


{% block title %}Logs{% endblock %}
{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Logs</h3>
            </div>
            <table class="styled-table">
                <thead>
                    <tr>
                        <th>Time</th>
                        <th>Status</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    {% for log in Logs reversed%}
                    <tr>
                        <td>{{ log.check_time}}</td>
                        <td>{{ log.status}}</td>
                        <td>{{ log.description}}</td>
                    </tr>
                    {% endfor %}
                </tbody>

                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

webmonit/templates/webmonit/problems.html
{% extends "webmonit/base.html" %}

{% block title %}Homepage{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Webpages with problems</h3>
            </div>

            <ul class="list-group">
                {% for page in Pages %}
                <li class="list-group-item">
                    <strong>{{ page.name }}</strong>
                    <span class="pull-right">
                        <a href="{% url 'webmonit:page_log' page.id %}" class="btn btn-info btn-xs">logs</a> &nbsp;
                        <a href="{% url 'webmonit:detail' page.id %}" class="btn btn-default btn-xs">details</a> &nbsp;
                        &#10004;
                    </span>
                </li>
                {% endfor %}
            </ul>

        </div>
    </div>
</div>
{% endblock %}